"""Equivalence LLM-judge verifier — generated by nemotron_gym (Harbor-aligned).

For open-ended science / QA datasets whose grading is inherently an
*equivalence* judgment: the agent produces a free-form answer (with the final
answer boxed in ``\\boxed{...}`` per the task prompt) and the verifier asks an
LLM judge whether that answer is *scientifically equivalent* to a reference
answer. This is the right tool when there is a known gold reference but the
surface form is open-ended (paragraph explanations, different phrasings,
equivalent derivations) so deterministic string match would spuriously fail.

Follows the same litellm + boxed-score protocol as ``llm_judge.py``:
  - Calls the LLM via ``litellm.completion`` (multi-provider).
  - Default model ``openai/gpt-4o-mini`` (Harbor's default judge).
  - Env var overrides: ``JUDGE_MODEL``, ``OPENAI_BASE_URL``, ``OPENAI_API_KEY``
    (propagated into the verifier container via ``LLM_JUDGE_TASK_TOML``).
  - ``temperature=0``, ``timeout=300``.
  - Reads the agent's answer from ``/app/response.txt`` (Harbor's strongreject
    path), falling back to ``/app/answer.txt`` (legacy).
  - Extracts the LAST ``\\boxed{...}`` from the agent response (balanced braces)
    as the candidate answer; falls back to the full response text if no box.
  - Judge returns a score in ``\\boxed{<float in [0,1]>}`` on the last line;
    score >= threshold -> reward 1, else reward 0. (Equivalence is a binary
    grade, so we threshold to {0,1} rather than passing the raw float.)

verifier_data.json schema:
  {
    "instruction": str,                 # the science question (for judge context)
    "reference_answer": str,            # the gold reference answer (REQUIRED)
    "judge_prompt_template": str,       # uses {instruction} {reference_answer}
                                        #   {candidate} placeholders; default below
    "judge_system_prompt": str (optional, default below),
    "score_threshold": float (default 0.5),
    "judge_model": str (optional, overrides JUDGE_MODEL env var fallback),
  }
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Equivalence LLM-judge verifier — generated by nemotron_gym (Harbor-aligned)."""
from __future__ import annotations

import json
import os
import pathlib
import re
import sys
from collections import defaultdict

REWARD = pathlib.Path("/logs/verifier/reward.txt")
RESPONSE_PRIMARY = pathlib.Path("/app/response.txt")
RESPONSE_LEGACY = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

DEFAULT_JUDGE_MODEL = "openai/gpt-4o-mini"
JUDGE_TIMEOUT_S = 300
MAX_RESPONSE_BYTES = 256 * 1024

DEFAULT_SYSTEM_PROMPT = (
    "You are an impartial science grader. You judge whether a candidate answer "
    "is scientifically equivalent to a reference answer for an open-ended "
    "question. Equivalent means it conveys the same correct core explanation / "
    "result, even if phrased differently, more or less verbose, or using "
    "different but equivalent notation. It is NOT equivalent if it states a "
    "wrong mechanism, a wrong result, contradicts the reference, or omits the "
    "key point. Provide your final score in \\boxed{...} on the last line."
)

DEFAULT_TEMPLATE = """You are grading an open-ended science question by equivalence to a reference answer.

Question:
{instruction}

Reference answer (gold):
{reference_answer}

Candidate answer (to grade):
{candidate}

Decide whether the candidate answer is scientifically equivalent to the reference
answer (same correct core explanation/result; phrasing may differ). Output 1.0 if
equivalent (correct), 0.0 if not equivalent (wrong, contradictory, or missing the
key point). You may use an intermediate value only if partially correct.
End with \\boxed{{<score>}} on the last line."""


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _read_response() -> str | None:
    for path in (RESPONSE_PRIMARY, RESPONSE_LEGACY):
        if path.exists():
            text = path.read_text(errors="replace")[:MAX_RESPONSE_BYTES]
            if text.strip():
                return text
    return None


def _extract_boxed(text: str) -> str | None:
    """Return the content of the LAST balanced \\boxed{...}, or None."""
    idx = text.rfind(r"\boxed{")
    if idx < 0:
        return None
    depth = 0
    start = idx + len(r"\boxed{")
    for i in range(start, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            if depth == 0:
                return text[start:i].strip()
            depth -= 1
    return None


def _extract_score(text: str) -> float:
    m = re.search(r"\\boxed\{\s*([\d.]+)\s*\}", text)
    if m:
        try:
            return max(0.0, min(1.0, float(m.group(1))))
        except ValueError:
            pass
    for m2 in re.finditer(r"\b(0\.\d+|1\.0|0|1)\b", text):
        try:
            return max(0.0, min(1.0, float(m2.group(1))))
        except ValueError:
            continue
    return 0.0


def _resolve_model(data: dict) -> str:
    cfg = data.get("judge_model")
    if isinstance(cfg, str) and cfg.strip():
        return cfg.strip()
    return os.environ.get("JUDGE_MODEL", DEFAULT_JUDGE_MODEL).strip() or DEFAULT_JUDGE_MODEL


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    reference = data.get("reference_answer", "")
    if not isinstance(reference, str) or not reference.strip():
        print("reference_answer missing/empty", file=sys.stderr)
        return 0
    response_text = _read_response()
    if response_text is None:
        print(
            "Agent response not found at /app/response.txt or /app/answer.txt",
            file=sys.stderr,
        )
        return 0

    candidate = _extract_boxed(response_text)
    if candidate is None or not candidate.strip():
        # Agent did not box its answer — fall back to the full response text.
        candidate = response_text.strip()
        print("note: no \\boxed{} found; using full response as candidate")

    instruction = data.get("instruction", "")
    template = data.get("judge_prompt_template") or DEFAULT_TEMPLATE
    system_prompt = data.get("judge_system_prompt") or DEFAULT_SYSTEM_PROMPT

    fmt_kwargs = defaultdict(str)
    fmt_kwargs["instruction"] = instruction
    fmt_kwargs["reference_answer"] = reference
    fmt_kwargs["candidate"] = candidate
    # Back-compat alias for templates that use {response}.
    fmt_kwargs["response"] = candidate
    try:
        prompt = template.format_map(fmt_kwargs)
    except (KeyError, IndexError, ValueError) as e:
        print(f"template format error ({e}); using default")
        prompt = DEFAULT_TEMPLATE.format_map(fmt_kwargs)

    try:
        from litellm import completion
    except ImportError:
        print("litellm unavailable in container", file=sys.stderr)
        return 0

    model = _resolve_model(data)
    try:
        resp = completion(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt},
            ],
            temperature=0,
            timeout=JUDGE_TIMEOUT_S,
        )
    except Exception as e:
        print(f"judge API error ({model}): {e}", file=sys.stderr)
        return 0
    if not resp or not resp.choices:
        print(f"judge ({model}) returned no choices", file=sys.stderr)
        return 0
    judge_output = (resp.choices[0].message.content or "").strip()
    print(f"Judge model: {model}")
    print(f"Candidate (boxed/extracted):\n{candidate[:1000]}")
    print(f"Judge output:\n{judge_output[:2000]}")
    score = _extract_score(judge_output)
    threshold = float(data.get("score_threshold", 0.5))
    print(f"Extracted score: {score} (threshold={threshold})")
    return 1 if score >= threshold else 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
