"""ARC-AGI python_inductive verifier: exec agent's transform() on held test input.

The agent is asked to write a Python function
    def transform(grid: list[list[int]]) -> list[list[int]]:
wrapped in a ```python ... ``` fence. We extract the code (from /app/solution.py
if present, else /app/answer.txt), exec it in a SUBPROCESS with a timeout in the
task sandbox, call transform() on each held test input, and compare the returned
grid to the expected output. Reward 1 iff ALL test cases match exactly.

Security: the agent code runs only inside Harbor's disposable task container
(python:3.11-slim-bookworm). The verifier never execs/evals anything from
verifier_data.json (that holds only the JSON grids); it execs the agent's own
submission via a subprocess with a hard timeout, exactly as the competitive
coding (stdio_diff) verifier does.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""ARC-AGI python_inductive grid-transform verifier — generated by nemotron_gym.

verifier_data.json:
  {"test_cases": [{"input": [[int,...],...], "output": [[int,...],...]}, ...]}

Extracts the agent's `transform` function source, runs it in a subprocess
against each test input, compares to expected output. 1/0 -> reward.txt.
"""
from __future__ import annotations

import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile

REWARD = pathlib.Path("/logs/verifier/reward.txt")
SOLUTION = pathlib.Path("/app/solution.py")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")
TIMEOUT_S = 30


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _extract_code(text: str) -> str | None:
    """Pull python source from the agent output.

    Prefers the LAST ```python ... ``` fenced block; falls back to the last
    generic ``` ... ``` block; else, if a bare `def transform` is present,
    uses the whole text.
    """
    # Fenced ```python blocks.
    blocks = re.findall(r"```(?:python|py)\s*\n(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if blocks:
        return blocks[-1]
    # Generic fenced blocks.
    blocks = re.findall(r"```\s*\n(.*?)```", text, flags=re.DOTALL)
    for b in reversed(blocks):
        if "def transform" in b:
            return b
    if "def transform" in text:
        return text
    return None


_RUNNER = r"""
import json, sys
{user_code}

def _main():
    cases = json.load(open(sys.argv[1]))
    results = []
    for case in cases:
        out = transform([list(r) for r in case["input"]])
        # Normalize to list-of-lists of ints.
        norm = [[int(v) for v in row] for row in out]
        results.append(norm)
    print(json.dumps(results))

_main()
"""


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    cases = data.get("test_cases")
    if not (isinstance(cases, list) and cases):
        print("test_cases missing/empty", file=sys.stderr)
        return 0

    src = None
    if SOLUTION.exists():
        src = SOLUTION.read_text(errors="replace")
    if (src is None or "def transform" not in src) and ANSWER.exists():
        src = ANSWER.read_text(errors="replace")
    if not src:
        print("no /app/solution.py or /app/answer.txt with code", file=sys.stderr)
        return 0
    code = _extract_code(src)
    if code is None:
        print("could not extract a transform() function from agent output")
        return 0

    runner = _RUNNER.replace("{user_code}", code)
    env = {k: v for k, v in os.environ.items() if k in ("PATH", "HOME", "LANG", "LC_ALL")}
    env.setdefault("PATH", "/usr/local/bin:/usr/bin:/bin")

    with tempfile.TemporaryDirectory() as td:
        runner_path = os.path.join(td, "runner.py")
        cases_path = os.path.join(td, "cases.json")
        with open(runner_path, "w") as f:
            f.write(runner)
        with open(cases_path, "w") as f:
            json.dump(cases, f)
        try:
            res = subprocess.run(
                ["python3", runner_path, cases_path],
                capture_output=True,
                text=True,
                timeout=TIMEOUT_S,
                env=env,
                cwd=td,
            )
        except subprocess.TimeoutExpired:
            print(f"TIMEOUT after {TIMEOUT_S}s")
            return 0
        except Exception as e:
            print(f"exec error: {e}")
            return 0

    if res.returncode != 0:
        print(f"runner failed (rc={res.returncode})")
        print(f"stderr: {res.stderr[:500]!r}")
        return 0
    try:
        got = json.loads(res.stdout.strip().splitlines()[-1])
    except Exception as e:
        print(f"could not parse runner output: {e}; stdout={res.stdout[:300]!r}")
        return 0

    if len(got) != len(cases):
        print(f"result count mismatch: {len(got)} vs {len(cases)}")
        return 0
    for i, (g, case) in enumerate(zip(got, cases)):
        want = [[int(v) for v in row] for row in case["output"]]
        if g != want:
            print(f"case {i}: MISMATCH got_dims={len(g)}x{len(g[0]) if g else 0} "
                  f"want_dims={len(want)}x{len(want[0]) if want else 0}")
            return 0
    print(f"all {len(cases)} test case(s) matched")
    return 1


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
