"""ARC-AGI transductive verifier: parse agent grid, compare to expected grid.

The agent is asked (per the dataset system prompt) to emit:
    \boxed{solution}
where solution is "an array of rows separated by newlines, values by spaces".

In practice the dataset's own few-shot examples render grids as
concatenated single-digit rows (no spaces, e.g. "292"), so the model may
emit either form. Cell values are always single digits 0-9, which makes the
concatenated form unambiguous. This verifier therefore parses BOTH:
  - space/comma/tab separated values per row
  - bare concatenated single-digit rows
It extracts the LAST \boxed{...} if present, else parses the whole answer
file as a grid. Reward 1 iff the parsed grid matches expected_output exactly
(cell-by-cell, same dimensions).
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""ARC-AGI transductive grid-match verifier — generated by nemotron_gym.

verifier_data.json:
  {"expected_output": [[int, ...], ...]}

Reads /app/answer.txt, parses a grid, compares to expected_output.
Writes 1/0 to /logs/verifier/reward.txt.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _last_boxed(text: str) -> str | None:
    """Return the content of the LAST top-level \\boxed{...}, brace-balanced."""
    idx = text.rfind("\\boxed")
    if idx == -1:
        return None
    i = text.find("{", idx)
    if i == -1:
        return None
    depth = 0
    j = i
    while j < len(text):
        ch = text[j]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1:j]
        j += 1
    # Unbalanced — take rest of string after the opening brace.
    return text[i + 1:]


def _parse_row(line: str) -> list[int] | None:
    """Parse one grid row into a list of ints. Handles separated and bare forms."""
    s = line.strip()
    if not s:
        return None
    # Strip surrounding list/tuple/quote punctuation that a model might add.
    s = s.strip("[](){}'\"")
    if not s:
        return None
    # Separated form: tokens split on commas/whitespace.
    if re.search(r"[,\s]", s):
        toks = re.split(r"[,\s]+", s.strip())
        toks = [t.strip("[](){}'\"") for t in toks if t.strip("[](){}'\"") != ""]
        try:
            return [int(t) for t in toks]
        except ValueError:
            return None
    # Bare concatenated single-digit form: "292".
    if re.fullmatch(r"-?\d+", s) and "-" not in s:
        return [int(c) for c in s]
    # Single negative or multi-digit token with no separators -> one cell.
    try:
        return [int(s)]
    except ValueError:
        return None


def _parse_grid(text: str) -> list[list[int]] | None:
    text = text.strip()
    if not text:
        return None
    # Try JSON list-of-lists first.
    try:
        obj = json.loads(text)
        if (
            isinstance(obj, list)
            and obj
            and all(isinstance(r, list) for r in obj)
            and all(isinstance(v, int) for r in obj for v in r)
        ):
            return [list(r) for r in obj]
    except (ValueError, TypeError):
        pass
    # Line-based parse.
    rows: list[list[int]] = []
    for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        parsed = _parse_row(line)
        if parsed is not None:
            rows.append(parsed)
    if not rows:
        return None
    return rows


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_output")
    if not (isinstance(expected, list) and expected and all(isinstance(r, list) for r in expected)):
        print("expected_output malformed", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    boxed = _last_boxed(raw)
    candidate_texts = []
    if boxed is not None:
        candidate_texts.append(boxed)
    candidate_texts.append(raw)
    grid = None
    for ct in candidate_texts:
        grid = _parse_grid(ct)
        if grid is not None:
            break
    if grid is None:
        print("could not parse any grid from answer")
        return 0
    exp = [[int(v) for v in r] for r in expected]
    if len(grid) != len(exp):
        print(f"row count mismatch: got {len(grid)} want {len(exp)}")
        return 0
    for i, (gr, er) in enumerate(zip(grid, exp)):
        if list(gr) != list(er):
            print(f"row {i} mismatch: got {gr} want {er}")
            return 0
    print(f"grid match: {len(exp)}x{len(exp[0])}")
    return 1


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
