"""Hybrid IFEval-constraint + LLM-judge verifier for CFBench.

`nvidia/Nemotron-RL-CFBench-v1` mixes two kinds of checks per row:

  * DETERMINISTIC instruction constraints (`instructions`): IFEval-style
    structured constraints with an `instruction_id` and inline kwargs, e.g.
    ``{"instruction_id": "detectable_format:number_bullet_lists",
       "relation": "equal to", "num_bullets": 5}``. These are graded by
    self-contained Python checks — no network, no key.
  * SUBJECTIVE judge questions (`llm_judge`): natural-language yes/no checks,
    e.g. ``{"content": "Are these analysis results listed in order of
    severity?"}``. These are graded by an LLM judge (litellm / OpenAI).

This verifier runs BOTH and combines them. NOTE: CFBench's instruction schema
is materially different from the original `Nemotron-RL-instruction_following`
schema that `ifeval_constraints.py` targets:

  * kwargs are inline on each instruction dict (not a parallel `kwargs` list);
  * the relation vocabulary is {"equal to", "less than", "more than",
    "greater than", "at least", "at most"} — NOT the {"at least", "less than",
    "at most", "equal"} set the original `_check_relation` understands;
  * several kwarg key names differ (e.g. `num_unique`, `num_sentences`,
    `section_splitter`).

So we cannot reuse `IFEVAL_VERIFIER_PY` verbatim. This module re-implements the
constraint logic with CFBench semantics (porting the IFEval check bodies where
they apply) and adds CFBench-native deterministic checks.

Instruction-id routing (decided at conversion time, recorded in
verifier_data.json):

  * "det"   — a deterministic check below grades it.
  * "judge" — inherently SUBJECTIVE (stylistic / situational / linguistic /
              ambiguous-unicode). The converter rewrites the constraint into a
              natural-language yes/no question appended to the judge question
              list, so it is STILL CHECKED (not silently passed).

Combination rule (documented, enforced in `main`):

    reward = 1  iff
        (every deterministic constraint in `det_constraints` PASSes)
      AND
        (every judge question in `judge_questions` scores >= score_threshold)

    Degenerate cases:
      * no det_constraints and no judge_questions  -> 0 (nothing to grade;
        such rows are skipped at conversion time, so this should not occur).
      * det_constraints only  -> reward = deterministic AND-reduction.
      * judge_questions only  -> reward = judge AND-reduction.

    The judge is invoked ONCE; it returns a per-question score list. A missing
    OPENAI_API_KEY makes the judge portion fail (score 0) — the deterministic
    portion still runs with no key. Final reward is written as 0/1.

verifier_data.json schema produced by the converter:
  {
    "det_constraints": [ {"instruction_id": str, ...inline kwargs...}, ... ],
    "judge_questions": [ str, ... ],          # subjective checks + routed insts
    "instruction": str,                        # the task prompt (judge context)
    "score_threshold": float (default 0.7),
    "judge_model": str (optional)
  }
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Hybrid IFEval-constraint + LLM-judge verifier — generated by nemotron_gym."""
from __future__ import annotations

import json
import os
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER_PRIMARY = pathlib.Path("/app/answer.txt")
ANSWER_LEGACY = pathlib.Path("/app/response.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

DEFAULT_JUDGE_MODEL = "openai/gpt-4o-mini"
JUDGE_TIMEOUT_S = 300


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


# === text helpers ===========================================================

_PARA_SEP = re.compile(r"\n\s*\n+")
# Sentence splitter that respects CJK terminators as well as ASCII ones.
_SENT_SPLIT = re.compile(r"(?<=[.!?。！？])\s*")
_WORD_RE = re.compile(r"[^\W\d_]+", flags=re.UNICODE)


def _paragraphs(text: str) -> list:
    return [p for p in _PARA_SEP.split(text.strip()) if p.strip()]


def _sentences(text: str) -> list:
    return [s.strip() for s in _SENT_SPLIT.split(text.strip()) if s.strip()]


def _words(text: str) -> list:
    # Unicode-aware word tokens (letters across scripts); excludes digits/punct.
    return _WORD_RE.findall(text)


def _check_relation(actual, rel, n):
    rel = (rel or "").strip().lower()
    if rel in ("at least", "greater than or equal to", ">="):
        return actual >= n
    if rel in ("at most", "less than or equal to", "<="):
        return actual <= n
    if rel in ("less than", "fewer than", "<"):
        return actual < n
    if rel in ("more than", "greater than", ">"):
        return actual > n
    if rel in ("equal to", "equal", "exactly", "=", "=="):
        return actual == n
    # Unknown relation -> treat as failure (do not silently pass).
    return None


def _as_int(v):
    if isinstance(v, bool):
        return None
    if isinstance(v, int):
        return v
    if isinstance(v, str) and re.fullmatch(r"-?\d+", v.strip()):
        return int(v.strip())
    if isinstance(v, float) and v.is_integer():
        return int(v)
    return None


# === deterministic constraint implementations ==============================

CONSTRAINTS: dict = {}


def constraint(*names):
    def wrap(fn):
        for nm in names:
            CONSTRAINTS[nm] = fn
        return fn
    return wrap


def _rel_check(actual, kw, num_key, rel_key="relation", default_rel="equal to"):
    n = _as_int(kw.get(num_key))
    if n is None:
        return False, f"missing/invalid {num_key}={kw.get(num_key)!r}"
    rel = kw.get(rel_key, default_rel)
    res = _check_relation(actual, rel, n)
    if res is None:
        return False, f"unsupported relation {rel!r}"
    return res, f"actual={actual} rel={rel!r} n={n}"


# --- length / counts ---------------------------------------------------------

@constraint("length_constraints:number_words")
def _number_words(text, kw):
    return _rel_check(len(_words(text)), kw, "num_words", default_rel="at least")


@constraint("length_constraints:number_characters")
def _number_characters(text, kw):
    return _rel_check(len(text), kw, "num_chars")


@constraint("length_constraints:unique_words")
def _unique_words(text, kw):
    uniq = len({w.lower() for w in _words(text)})
    return _rel_check(uniq, kw, "num_unique")


@constraint("detectable_format:number_paragraphs")
def _number_paragraphs(text, kw):
    return _rel_check(len(_paragraphs(text)), kw, "num_paragraphs")


@constraint("detectable_format:sentence_count")
def _sentence_count(text, kw):
    return _rel_check(len(_sentences(text)), kw, "num_sentences")


@constraint("detectable_format:sentences_per_paragraph")
def _sentences_per_paragraph(text, kw):
    n = _as_int(kw.get("num_sentences"))
    if n is None:
        return False, "missing num_sentences"
    rel = kw.get("relation", "equal to")
    paras = _paragraphs(text)
    if not paras:
        return False, "no paragraphs"
    for i, p in enumerate(paras):
        res = _check_relation(len(_sentences(p)), rel, n)
        if res is None:
            return False, f"unsupported relation {rel!r}"
        if not res:
            return False, f"paragraph {i} has {len(_sentences(p))} sentences (need {rel} {n})"
    return True, f"all {len(paras)} paragraphs satisfy {rel} {n} sentences"


@constraint("length_constraints:word_repetition")
def _word_repetition(text, kw):
    mx = _as_int(kw.get("max_repeats"))
    if mx is None:
        return False, "missing max_repeats"
    counts: dict = {}
    for w in _words(text):
        wl = w.lower()
        counts[wl] = counts.get(wl, 0) + 1
    worst = max(counts.values()) if counts else 0
    return worst <= mx, f"max word repetition={worst} allowed<={mx}"


@constraint("length_constraints:sentence_length")
def _sentence_length(text, kw):
    mx = _as_int(kw.get("max_words"))
    if mx is None:
        return False, "missing max_words"
    sents = _sentences(text)
    if not sents:
        return False, "no sentences"
    for i, s in enumerate(sents):
        wc = len(_words(s))
        if wc > mx:
            return False, f"sentence {i} has {wc} words (>{mx})"
    return True, f"all {len(sents)} sentences <= {mx} words"


@constraint("length_constraints:word_length")
def _word_length(text, kw):
    lo = _as_int(kw.get("min_length"))
    hi = _as_int(kw.get("max_length"))
    ws = _words(text)
    if not ws:
        return False, "no words"
    for w in ws:
        L = len(w)
        if lo is not None and L < lo:
            return False, f"word {w!r} shorter than {lo}"
        if hi is not None and L > hi:
            return False, f"word {w!r} longer than {hi}"
    return True, f"all {len(ws)} words within [{lo},{hi}]"


@constraint("length_constraints:paragraph_length")
def _paragraph_length(text, kw):
    n = _as_int(kw.get("words_per_paragraph"))
    if n is None:
        return False, "missing words_per_paragraph"
    rel = kw.get("relation", "less than")
    paras = _paragraphs(text)
    if not paras:
        return False, "no paragraphs"
    for i, p in enumerate(paras):
        res = _check_relation(len(_words(p)), rel, n)
        if res is None:
            return False, f"unsupported relation {rel!r}"
        if not res:
            return False, f"paragraph {i} has {len(_words(p))} words (need {rel} {n})"
    return True, f"all paragraphs satisfy {rel} {n} words"


@constraint("detectable_format:max_paragraph_length")
def _max_paragraph_length(text, kw):
    mx = _as_int(kw.get("max_chars"))
    if mx is None:
        return False, "missing max_chars"
    paras = _paragraphs(text)
    if not paras:
        return False, "no paragraphs"
    worst = max(len(p) for p in paras)
    return worst <= mx, f"longest paragraph={worst} chars allowed<={mx}"


# --- keywords ----------------------------------------------------------------

def _word_count_ci(text, kw_word):
    # Unicode-aware: count occurrences as standalone tokens (handles CJK where
    # \b doesn't apply by also allowing a raw substring count fallback).
    low = text.lower()
    kw_low = kw_word.lower()
    # Token-boundary count for latin-ish words.
    bounded = re.findall(r"(?<!\w)" + re.escape(kw_low) + r"(?!\w)", low)
    if bounded:
        return len(bounded)
    # Fallback: plain substring count (CJK / no word boundaries).
    return low.count(kw_low) if kw_low else 0


@constraint("keywords:frequency", "keywords:word_count_different_numbers")
def _kw_frequency(text, kw):
    keyword = kw.get("keyword")
    if not isinstance(keyword, str):
        return False, "missing keyword"
    c = _word_count_ci(text, keyword)
    return _rel_check(c, kw, "frequency", default_rel="at least")


@constraint("keywords:existence")
def _kw_existence(text, kw):
    kws = kw.get("keywords", [])
    if not isinstance(kws, list):
        return False, "keywords must be list"
    low = text.lower()
    missing = [w for w in kws if isinstance(w, str) and w.lower() not in low]
    return not missing, f"missing={missing}"


@constraint("keywords:forbidden_words")
def _forbidden_words(text, kw):
    forb = kw.get("forbidden_words", [])
    if not isinstance(forb, list):
        return False, "forbidden_words must be list"
    low = text.lower()
    hits = [w for w in forb if isinstance(w, str)
            and re.search(r"(?<!\w)" + re.escape(w.lower()) + r"(?!\w)", low)]
    return not hits, f"hits={hits}"


@constraint("keywords:letter_frequency")
def _letter_frequency(text, kw):
    letter = kw.get("letter")
    if not isinstance(letter, str) or len(letter) != 1:
        return False, f"bad letter={letter!r}"
    cnt = sum(1 for c in text if c.lower() == letter.lower())
    n = _as_int(kw.get("let_frequency"))
    if n is None:
        return False, "missing let_frequency"
    rel = kw.get("let_relation", "at least")
    res = _check_relation(cnt, rel, n)
    if res is None:
        return False, f"unsupported relation {rel!r}"
    return res, f"letter={letter!r} count={cnt} rel={rel!r} n={n}"


@constraint("keywords:positioning")
def _kw_positioning(text, kw):
    keyword = kw.get("keyword")
    pos = _as_int(kw.get("position"))
    if not isinstance(keyword, str) or pos is None:
        return False, "bad kwargs"
    # `position` is a 1-based character index at which the keyword must start.
    idx = pos - 1
    if idx < 0 or idx + len(keyword) > len(text):
        return False, f"position {pos} out of range (len={len(text)})"
    seg = text[idx:idx + len(keyword)]
    return seg == keyword, f"at pos {pos}: {seg!r} (want {keyword!r})"


@constraint("keywords:palindrome_word")
def _palindrome_word(text, kw):
    minL = _as_int(kw.get("min_length")) or 3
    for w in _words(text):
        wl = w.lower()
        if len(wl) >= minL and wl == wl[::-1]:
            return True, f"palindrome={wl!r}"
    return False, f"no palindrome of length >= {minL}"


# --- startend ----------------------------------------------------------------

@constraint("startend:end_checker")
def _end_checker(text, kw):
    ep = kw.get("end_phrase")
    if not isinstance(ep, str):
        return False, "missing end_phrase"
    return text.rstrip().endswith(ep.rstrip()), f"ends_with={ep!r}"


@constraint("startend:start_checker")
def _start_checker(text, kw):
    sp = kw.get("start_phrase")
    if not isinstance(sp, str):
        return False, "missing start_phrase"
    return text.lstrip().startswith(sp.lstrip()), f"starts_with={sp!r}"


@constraint("startend:wrap_checker")
def _wrap_checker(text, kw):
    wp = kw.get("wrap_phrase")
    if not isinstance(wp, str):
        return False, "missing wrap_phrase"
    s = text.strip()
    ok = s.startswith(wp) and s.endswith(wp) and len(s) >= 2 * len(wp)
    return ok, f"wrapped_by={wp!r}: {ok}"


@constraint("startend:quotation")
def _quotation(text, kw):
    s = text.strip()
    ok = (
        (s.startswith('"') and s.endswith('"'))
        or (s.startswith("“") and s.endswith("”"))
        or (s.startswith("'") and s.endswith("'"))
        or (s.startswith("「") and s.endswith("」"))
    )
    return ok, f"quoted={ok}"


# --- detectable_format -------------------------------------------------------

@constraint("detectable_format:title")
def _title(text, kw):
    return bool(re.search(r"<<[^<>\n]+>>", text)), "title_marker <<...>>"


@constraint("detectable_format:number_bullet_lists")
def _bullet_lists(text, kw):
    bullets = sum(1 for line in text.splitlines()
                  if re.match(r"^\s*[\*\-•・]\s+", line))
    return _rel_check(bullets, kw, "num_bullets")


@constraint("detectable_format:numbered_list")
def _numbered_list(text, kw):
    items = sum(1 for line in text.splitlines()
                if re.match(r"^\s*\d+[\.\)．、]\s+", line))
    return _rel_check(items, kw, "num_numbered_items")


@constraint("detectable_format:multiple_sections")
def _multiple_sections(text, kw):
    splitter = kw.get("section_splitter") or kw.get("section_spliter") or "Section"
    if not isinstance(splitter, str):
        return False, "bad splitter"
    pat = re.compile(re.escape(splitter) + r"\s*\d+", flags=re.IGNORECASE)
    actual = len(pat.findall(text))
    return _rel_check(actual, kw, "num_sections", default_rel="at least")


@constraint("detectable_format:table")
def _table(text, kw):
    min_rows = _as_int(kw.get("min_rows")) or 1
    min_cols = _as_int(kw.get("min_cols")) or 1
    # Markdown-style pipe tables: rows are lines with >= min_cols-1 pipes that
    # delimit cells. Count data rows that have enough columns.
    rows = []
    for line in text.splitlines():
        if line.count("|") >= 1:
            cells = [c for c in line.strip().strip("|").split("|")]
            # Skip markdown separator rows (---|---).
            if re.fullmatch(r"[\s:\-|]+", line.strip()):
                continue
            if len(cells) >= min_cols:
                rows.append(cells)
    return len(rows) >= min_rows, f"table rows>={min_rows}? got {len(rows)} (cols>={min_cols})"


@constraint("detectable_format:nested_list")
def _nested_list(text, kw):
    min_depth = _as_int(kw.get("min_depth")) or 2
    # Depth = distinct leading-indent levels among bullet/numbered list lines.
    indents = set()
    for line in text.splitlines():
        m = re.match(r"^(\s*)([\*\-•]|\d+[\.\)])\s+", line)
        if m:
            indents.add(len(m.group(1).replace("\t", "    ")))
    levels = len(indents)
    return levels >= min_depth, f"nesting levels={levels} need>={min_depth}"


@constraint("detectable_format:heading_depth")
def _heading_depth(text, kw):
    levels = kw.get("levels")
    want = set()
    if isinstance(levels, list):
        for x in levels:
            xi = _as_int(x)
            if xi is not None:
                want.add(xi)
    elif _as_int(levels) is not None:
        want.add(_as_int(levels))
    if not want:
        return False, "missing/invalid levels"
    found = set()
    for line in text.splitlines():
        m = re.match(r"^(#{1,6})\s+\S", line)
        if m:
            found.add(len(m.group(1)))
    ok = want.issubset(found)
    return ok, f"heading levels found={sorted(found)} need={sorted(want)}"


@constraint("detectable_format:json_format")
def _json_format(text, kw):
    s = text.strip()
    fence = re.match(r"^```(?:json)?\s*\n(.*)\n```\s*$", s, flags=re.DOTALL)
    if fence:
        s = fence.group(1).strip()
    try:
        json.loads(s)
        return True, "json_parses"
    except Exception as e:
        return False, f"json_parse_error: {e}"


# --- detectable_content ------------------------------------------------------

@constraint("detectable_content:postscript")
def _postscript(text, kw):
    marker = kw.get("postscript_marker")
    if not isinstance(marker, str):
        return False, "missing postscript_marker"
    ok = marker in text
    return ok, f"postscript present={ok}"


@constraint("detectable_content:number_placeholders")
def _number_placeholders(text, kw):
    matches = re.findall(r"\[[^\[\]\n]+\]", text)
    return _rel_check(len(matches), kw, "num_placeholders", default_rel="at least")


@constraint("detectable_content:numeric_inclusion")
def _numeric_inclusion(text, kw):
    nums = re.findall(r"\d+(?:[.,]\d+)?", text)
    return _rel_check(len(nums), kw, "num_numbers")


# --- punctuation -------------------------------------------------------------

@constraint("punctuation:no_comma")
def _no_comma(text, kw):
    has = ("," in text) or ("，" in text) or ("、" in text)
    return not has, f"has_comma={has}"


@constraint("punctuation:no_period")
def _no_period(text, kw):
    has = ("." in text) or ("。" in text) or ("．" in text)
    return not has, f"has_period={has}"


@constraint("punctuation:end_rule")
def _end_rule(text, kw):
    allowed = kw.get("allowed")
    # CFBench passes `allowed` as a comma/space-separated STRING; SysBench passes
    # it as a LIST of terminal chars (e.g. ['.', '?', '!']). Support both.
    if isinstance(allowed, list):
        chars = {c for c in allowed if isinstance(c, str) and c}
        if not chars:
            return False, "empty allowed list"
        # SysBench semantics: EVERY sentence must end with an allowed terminator.
        sents = _sentences(text)
        if not sents:
            return False, "no sentences"
        for i, s in enumerate(sents):
            st = s.rstrip()
            if not st:
                continue
            if not any(st.endswith(a) for a in chars):
                return False, f"sentence[{i}] ends {st[-1]!r} not in {sorted(chars)}"
        return True, f"all sentences end with one of {sorted(chars)}"
    if not isinstance(allowed, str):
        return False, "missing allowed"
    # `allowed` is a comma/space separated list of acceptable terminal chars.
    chars = {c for c in allowed if not c.isspace() and c != ","}
    s = text.rstrip()
    if not s:
        return False, "empty"
    ok = s[-1] in chars
    return ok, f"last_char={s[-1]!r} allowed={sorted(chars)}"


@constraint("punctuation:question_exclaim")
def _question_exclaim(text, kw):
    marks = sum(text.count(c) for c in "?!？！")
    return _rel_check(marks, kw, "num_marks")


# --- change_case -------------------------------------------------------------

def _cased_letters(text):
    return [c for c in text if c.isalpha() and (c.lower() != c.upper())]


@constraint("change_case:lowercase")
def _all_lower(text, kw):
    letters = _cased_letters(text)
    if not letters:
        return False, "no cased letters"
    ok = all(c.islower() for c in letters)
    return ok, f"all_lower={ok}"


@constraint("change_case:all_caps")
def _all_caps(text, kw):
    letters = _cased_letters(text)
    if not letters:
        return False, "no cased letters"
    ok = all(c.isupper() for c in letters)
    return ok, f"all_caps={ok}"


@constraint("change_case:first_letter_cap")
def _first_letter_cap(text, kw):
    # First cased letter of each sentence must be uppercase.
    sents = _sentences(text)
    if not sents:
        return False, "no sentences"
    for s in sents:
        for c in s:
            if c.isalpha() and c.lower() != c.upper():
                if not c.isupper():
                    return False, f"sentence starts lowercase: {s[:20]!r}"
                break
    return True, "each sentence starts with uppercase"


@constraint("change_case:last_letter")
def _last_letter(text, kw):
    case = (kw.get("case") or "").lower()
    cased = _cased_letters(text)
    if not cased:
        return False, "no cased letters"
    last = cased[-1]
    if "upper" in case:
        return last.isupper(), f"last cased letter {last!r} upper?"
    if "lower" in case:
        return last.islower(), f"last cased letter {last!r} lower?"
    return False, f"unknown case={case!r}"


@constraint("change_case:capital_word_frequency")
def _capital_word_frequency(text, kw):
    all_caps = sum(1 for w in _words(text) if len(w) >= 2 and w.isupper())
    n = _as_int(kw.get("capital_frequency"))
    if n is None:
        return False, "missing capital_frequency"
    rel = kw.get("capital_relation", "at least")
    res = _check_relation(all_caps, rel, n)
    if res is None:
        return False, f"unsupported relation {rel!r}"
    return res, f"all_caps_words={all_caps} rel={rel!r} n={n}"


# --- change_case (SysBench additions) ---------------------------------------
# Appended additively for nvidia/Nemotron-RL-SysBench-v1; do not reorder.

@constraint("change_case:first_letter_sentence")
def _first_letter_sentence(text, kw):
    # Every sentence must begin with a capital (cased) letter.
    sents = _sentences(text)
    if not sents:
        return False, "no sentences"
    for i, s in enumerate(sents):
        for c in s:
            if c.isalpha() and c.lower() != c.upper():
                if not c.isupper():
                    return False, f"sentence[{i}] starts lowercase: {s[:30]!r}"
                break
    return True, f"all {len(sents)} sentences start with a capital"


@constraint("change_case:all_caps_target")
def _all_caps_target(text, kw):
    # The target string must appear written in ALL CAPS.
    target = kw.get("target_string")
    if not isinstance(target, str) or not target:
        return False, "missing target_string"
    ok = target.upper() in text
    return ok, f"target {target.upper()!r} (all-caps form) present={ok}"


@constraint("change_case:lowercase_target")
def _lowercase_target(text, kw):
    # The target string must appear written in lowercase.
    target = kw.get("target_string")
    if not isinstance(target, str) or not target:
        return False, "missing target_string"
    ok = target.lower() in text
    return ok, f"target {target.lower()!r} (lowercase form) present={ok}"


@constraint("change_case:first_letter_cap_target")
def _first_letter_cap_target(text, kw):
    # The target phrase must appear with its given (title) casing preserved.
    target = kw.get("target_string")
    if not isinstance(target, str) or not target:
        return False, "missing target_string"
    ok = target in text
    return ok, f"target {target!r} present (case-sensitive)={ok}"


@constraint("change_case:alternating")
def _alternating(text, kw):
    # Cased letters must alternate upper/lower with no two same-case adjacent.
    letters = _cased_letters(text)
    if len(letters) < 2:
        return False, "too few cased letters"
    for i in range(1, len(letters)):
        if letters[i].isupper() == letters[i - 1].isupper():
            return False, f"non-alternating at letter {i}: {letters[i-1]!r}{letters[i]!r}"
    return True, f"all {len(letters)} cased letters alternate"


@constraint("change_case:alternating_target")
def _alternating_target(text, kw):
    # The target string must appear written in alternating case (either phase).
    target = kw.get("target_string")
    if not isinstance(target, str) or not target:
        return False, "missing target_string"
    alt_a = "".join(c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(target))
    alt_b = "".join(c.lower() if i % 2 == 0 else c.upper() for i, c in enumerate(target))
    ok = alt_a in text or alt_b in text
    return ok, f"target {target!r} in alternating case={ok}"


# --- detectable_format (SysBench additions) ---------------------------------

@constraint("detectable_format:sentence_endings")
def _sentence_endings(text, kw):
    # Response must use at least `min_variants` distinct sentence-ending marks.
    min_variants = _as_int(kw.get("min_variants"))
    if min_variants is None:
        return False, "missing min_variants"
    enders = set(re.findall(r"[.!?。！？]", text))
    return len(enders) >= min_variants, f"distinct_enders={sorted(enders)} need>={min_variants}"


# === LLM judge ==============================================================

def _read_answer():
    for p in (ANSWER_PRIMARY, ANSWER_LEGACY):
        if p.exists():
            t = p.read_text(errors="replace")
            if t.strip():
                return t
    return None


def _extract_scores(text, n):
    """Pull n scores from the judge output.

    Preferred: a JSON array of 0/1 (or floats) after a SCORES: marker or a bare
    JSON array. Fallback: the first n numbers in [0,1] found in the text.
    """
    # Try a JSON array anywhere in the text (last one wins — most likely the
    # final answer).
    arrs = re.findall(r"\[[^\[\]]*\]", text)
    for raw in reversed(arrs):
        try:
            val = json.loads(raw)
        except Exception:
            continue
        if isinstance(val, list) and val and all(isinstance(x, (int, float)) for x in val):
            return [max(0.0, min(1.0, float(x))) for x in val]
    # Fallback: scan numbers.
    nums = []
    for m in re.finditer(r"\b(0\.\d+|1\.0|0|1)\b", text):
        try:
            nums.append(max(0.0, min(1.0, float(m.group(1)))))
        except ValueError:
            pass
    return nums[:n] if nums else []


def _run_judge(instruction, answer, questions, threshold, model):
    """Return list[bool] (one per question), or None on hard failure."""
    try:
        from litellm import completion
    except ImportError:
        print("litellm unavailable in container", file=sys.stderr)
        return None
    numbered = "\n".join(f"{i+1}. {q}" for i, q in enumerate(questions))
    system_prompt = (
        "You are a strict, impartial evaluator of whether a candidate response "
        "satisfies a list of yes/no requirements. For each requirement, output "
        "1.0 if the response clearly satisfies it and 0.0 if it does not. "
        "Be literal and conservative."
    )
    user_prompt = (
        "TASK / INSTRUCTION GIVEN TO THE WRITER:\n"
        f"{instruction}\n\n"
        "CANDIDATE RESPONSE:\n"
        f"{answer}\n\n"
        "REQUIREMENTS TO CHECK (in order):\n"
        f"{numbered}\n\n"
        "Return ONLY a JSON array of scores (one per requirement, in order), "
        "each 0.0 or 1.0. Example for 3 requirements: [1.0, 0.0, 1.0]\n"
        "On the final line, repeat the JSON array."
    )
    try:
        resp = completion(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0,
            timeout=JUDGE_TIMEOUT_S,
        )
    except Exception as e:
        print(f"judge API error ({model}): {e}", file=sys.stderr)
        return None
    if not resp or not resp.choices:
        print(f"judge ({model}) returned no choices", file=sys.stderr)
        return None
    out = (resp.choices[0].message.content or "").strip()
    print(f"Judge model: {model}")
    print(f"Judge output:\n{out[:2000]}")
    scores = _extract_scores(out, len(questions))
    if len(scores) < len(questions):
        # Could not parse a score for every question -> fail closed on the
        # missing ones.
        print(f"judge returned {len(scores)} scores for {len(questions)} questions; "
              "missing scored as fail", file=sys.stderr)
        scores = scores + [0.0] * (len(questions) - len(scores))
    return [s >= threshold for s in scores[:len(questions)]]


# === main ===================================================================

def main():
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    det = data.get("det_constraints", []) or []
    judge_qs = data.get("judge_questions", []) or []
    instruction = data.get("instruction", "")
    threshold = float(data.get("score_threshold", 0.7))
    model = (data.get("judge_model")
             or os.environ.get("JUDGE_MODEL", "").strip()
             or DEFAULT_JUDGE_MODEL)

    if not det and not judge_qs:
        print("nothing to grade", file=sys.stderr)
        return 0

    answer = _read_answer()
    if answer is None:
        print("/app/answer.txt missing or empty", file=sys.stderr)
        return 0

    # --- deterministic portion ---
    det_ok = True
    for c in det:
        if not isinstance(c, dict):
            print(f"[det] non-dict constraint {c!r} -> FAIL")
            det_ok = False
            continue
        iid = c.get("instruction_id")
        fn = CONSTRAINTS.get(iid)
        if fn is None:
            # Should not happen: converter only routes implemented ids to det.
            print(f"[det:{iid}] UNSUPPORTED — failing closed")
            det_ok = False
            continue
        try:
            ok, detail = fn(answer, c)
        except Exception as e:
            ok, detail = False, f"exception: {e}"
        print(f"[det:{iid}] {'PASS' if ok else 'FAIL'}: {detail}")
        if not ok:
            det_ok = False

    # --- judge portion ---
    judge_ok = True
    if judge_qs:
        results = _run_judge(instruction, answer, judge_qs, threshold, model)
        if results is None:
            print("[judge] judge unavailable -> FAIL", file=sys.stderr)
            judge_ok = False
        else:
            for q, r in zip(judge_qs, results):
                print(f"[judge] {'PASS' if r else 'FAIL'}: {q[:100]}")
            judge_ok = all(results)

    final = det_ok and judge_ok
    print(f"det_ok={det_ok} judge_ok={judge_ok} reward={int(final)}")
    return 1 if final else 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
