"""Multi-criterion YES/NO LLM-judge verifier for Inverse-IFEval.

The `nvidia/Nemotron-RL-InverseIFEval-v1` dataset grades each row with a LIST
of independent judge specs (`row["llm_judge"]`), each carrying:
  - `content`        : a fully self-contained grading prompt that embeds the
                       original instruction, a Standard/Reference Response, and
                       exactly ONE "Evaluation Criterion". It instructs the judge
                       to answer YES if the criterion is fully met, NO otherwise.
  - `pass_criteria`  : the answer that counts as a PASS for that criterion
                       (always "YES" in this dataset, but honored generically).

Unlike `llm_judge.py` (single call → 0..1 boxed score), this verifier runs ONE
judge call per criterion, parses a YES/NO verdict, and requires ALL criteria to
match their `pass_criteria` for `reward == 1`. This mirrors the upstream
all-criteria-must-pass grading (no partial credit), which is the correct
aggregation for instruction-following where every formatting constraint is a
hard requirement.

The agent's response is read from `/app/response.txt` (Harbor's judge-task
convention), falling back to `/app/answer.txt`. Each criterion's `content`
already contains the full grading rubric, so the verifier appends only the
candidate response before sending it to the judge.

verifier_data.json schema:
  {
    "instruction": str,                       # the prompt the agent saw (provenance)
    "criteria": [                             # one entry per llm_judge spec
      {"uid": int, "content": str, "pass_criteria": "YES"|"NO"},
      ...
    ],
    "judge_model": str (optional, overrides JUDGE_MODEL env var fallback),
  }

OPENAI_API_KEY (and optionally JUDGE_MODEL / OPENAI_BASE_URL) are propagated
into the verifier container via LLM_JUDGE_TASK_TOML.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Inverse-IFEval multi-criterion YES/NO judge — generated by nemotron_gym."""
from __future__ import annotations

import json
import os
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
RESPONSE_PRIMARY = pathlib.Path("/app/response.txt")
RESPONSE_LEGACY = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

DEFAULT_JUDGE_MODEL = "openai/gpt-4o-mini"
JUDGE_TIMEOUT_S = 300

SYSTEM_PROMPT = (
    "You are a meticulous instruction-following grading teacher. Grade strictly "
    "based on the criterion and the Standard Answer embedded in the prompt. "
    "Evaluate only what is explicitly present in the model's response. No partial "
    "credit. Answer with a single word, YES or NO, on the final line."
)

# The criterion `content` already ends with an "Answer YES ... NO" instruction.
# We append the candidate response and a final nudge to emit a bare verdict.
JUDGE_TEMPLATE = """{content}

## Model's Response
{response}

Now output your verdict. Reply with exactly one word on the last line: YES or NO."""


def _write_reward(score: float) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text(str(score))


def _read_response() -> str | None:
    for path in (RESPONSE_PRIMARY, RESPONSE_LEGACY):
        try:
            if path.exists():
                text = path.read_text(errors="replace")
                if text.strip():
                    return text
        except Exception:
            continue
    return None


def _extract_verdict(text: str) -> str | None:
    """Return 'YES' / 'NO' / None from a judge response.

    Prefers the last standalone YES/NO token (judges put the verdict last);
    falls back to any YES/NO occurrence.
    """
    if not text:
        return None
    upper = text.upper()
    matches = list(re.finditer(r"\b(YES|NO)\b", upper))
    if matches:
        return matches[-1].group(1)
    return None


def _resolve_model(data: dict) -> str:
    cfg = data.get("judge_model")
    if isinstance(cfg, str) and cfg.strip():
        return cfg.strip()
    return os.environ.get("JUDGE_MODEL", DEFAULT_JUDGE_MODEL).strip() or DEFAULT_JUDGE_MODEL


def main() -> float:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0.0
    data = json.loads(DATA.read_text())
    response_text = _read_response()
    if response_text is None:
        print(
            "Agent response not found at /app/response.txt or /app/answer.txt",
            file=sys.stderr,
        )
        return 0.0

    criteria = data.get("criteria")
    if not isinstance(criteria, list) or not criteria:
        print("no criteria in verifier_data.json", file=sys.stderr)
        return 0.0

    try:
        from litellm import completion
    except ImportError:
        print("litellm unavailable in container", file=sys.stderr)
        return 0.0

    model = _resolve_model(data)
    n_total = len(criteria)
    n_pass = 0

    for i, crit in enumerate(criteria):
        if not isinstance(crit, dict):
            print(f"criterion[{i}] not a dict; treating as fail", file=sys.stderr)
            return 0.0
        content = crit.get("content")
        expected = str(crit.get("pass_criteria", "YES")).strip().upper()
        if not isinstance(content, str) or not content.strip():
            print(f"criterion[{i}] missing content; treating as fail", file=sys.stderr)
            return 0.0

        prompt = JUDGE_TEMPLATE.format(content=content, response=response_text)
        try:
            resp = completion(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                temperature=0,
                timeout=JUDGE_TIMEOUT_S,
            )
        except Exception as e:
            print(f"judge API error on criterion[{i}] ({model}): {e}", file=sys.stderr)
            return 0.0
        if not resp or not resp.choices:
            print(f"judge ({model}) returned no choices for criterion[{i}]", file=sys.stderr)
            return 0.0
        judge_output = (resp.choices[0].message.content or "").strip()
        verdict = _extract_verdict(judge_output)
        uid = crit.get("uid", i)
        print(f"criterion uid={uid} expected={expected} verdict={verdict} :: {judge_output[:200]!r}")
        if verdict is None:
            print(f"criterion[{i}] unparseable verdict; treating as fail", file=sys.stderr)
            return 0.0
        if verdict == expected:
            n_pass += 1
        else:
            # All-or-nothing: one failed criterion → reward 0. Short-circuit.
            print(f"criterion uid={uid} FAILED (got {verdict}, need {expected}) — overall fail")
            return 0.0

    print(f"All {n_pass}/{n_total} criteria passed — reward 1.0")
    return 1.0


if __name__ == "__main__":
    score = 0.0
    try:
        score = float(main())
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0.0
    _write_reward(score)
'''
