"""Multi-criterion YES/NO rubric judge for multi-turn chat continuation tasks.

Used by `nvidia/Nemotron-RL-Instruction-Following-MultiTurnChat-v1`. Each row
carries a flat conversation (system + several user/assistant turns, ENDING on a
user turn) plus a `rubric`: a list of short criteria, each
  {"question": "<criterion>", "pass_criteria": "YES" | "NO"}.
The agent must write the FINAL assistant response (the answer to the last user
turn) to `/app/response.txt`; the judge then checks that response — IN THE
CONTEXT OF THE FULL DIALOGUE — against every rubric criterion.

Unlike `inverse_ifeval_judge.py` (whose `content` is a fully self-contained
grading prompt that already embeds the instruction + reference answer), here
each criterion is only a short question, so the verifier must itself supply the
conversation transcript and the candidate response to the judge. It runs ONE
judge call per criterion, parses a YES/NO verdict, and requires ALL criteria to
match their `pass_criteria` for `reward == 1` (no partial credit) — the faithful
aggregation for instruction-following where each criterion is a hard constraint.

The agent's response is read from `/app/response.txt` (Harbor's judge-task
convention), falling back to `/app/answer.txt`.

verifier_data.json schema:
  {
    "conversation": str,                      # flattened transcript the agent continued
    "instruction": str,                       # (provenance; == conversation here)
    "criteria": [                             # one entry per rubric question
      {"uid": int, "question": str, "pass_criteria": "YES"|"NO"},
      ...
    ],
    "judge_model": str (optional, overrides JUDGE_MODEL env var fallback),
  }

OPENAI_API_KEY (and optionally JUDGE_MODEL / OPENAI_BASE_URL) are propagated
into the verifier container via LLM_JUDGE_TASK_TOML.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Multi-turn rubric multi-criterion YES/NO judge — generated by nemotron_gym."""
from __future__ import annotations

import json
import os
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
RESPONSE_PRIMARY = pathlib.Path("/app/response.txt")
RESPONSE_LEGACY = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

DEFAULT_JUDGE_MODEL = "openai/gpt-4o-mini"
JUDGE_TIMEOUT_S = 300

SYSTEM_PROMPT = (
    "You are a meticulous instruction-following grading teacher. You are given a "
    "multi-turn conversation between a user and an AI assistant, the assistant's "
    "FINAL response (the answer to the last user message), and a single grading "
    "criterion phrased as a question. Judge ONLY the assistant's final response, "
    "but use the full conversation as context (e.g. for instructions given in "
    "earlier turns or the system prompt). Evaluate only what is explicitly "
    "present in the final response. No partial credit. Answer the criterion "
    "question with a single word, YES or NO, on the final line."
)

JUDGE_TEMPLATE = """## Conversation (the assistant's final response answers the last user message)
{conversation}

## Assistant's Final Response (this is what you are grading)
{response}

## Grading Criterion (answer this question about the final response)
{question}

Now output your verdict. Reply with exactly one word on the last line: YES or NO."""


def _write_reward(score: float) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text(str(score))


def _read_response() -> str | None:
    for path in (RESPONSE_PRIMARY, RESPONSE_LEGACY):
        try:
            if path.exists():
                text = path.read_text(errors="replace")
                if text.strip():
                    return text
        except Exception:
            continue
    return None


def _extract_verdict(text: str) -> str | None:
    """Return 'YES' / 'NO' / None from a judge response.

    Prefers the last standalone YES/NO token (judges put the verdict last).
    """
    if not text:
        return None
    upper = text.upper()
    matches = list(re.finditer(r"\b(YES|NO)\b", upper))
    if matches:
        return matches[-1].group(1)
    return None


def _resolve_model(data: dict) -> str:
    cfg = data.get("judge_model")
    if isinstance(cfg, str) and cfg.strip():
        return cfg.strip()
    return os.environ.get("JUDGE_MODEL", DEFAULT_JUDGE_MODEL).strip() or DEFAULT_JUDGE_MODEL


def main() -> float:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0.0
    data = json.loads(DATA.read_text())
    response_text = _read_response()
    if response_text is None:
        print(
            "Agent response not found at /app/response.txt or /app/answer.txt",
            file=sys.stderr,
        )
        return 0.0

    conversation = data.get("conversation") or data.get("instruction") or ""
    if not isinstance(conversation, str):
        conversation = str(conversation)

    criteria = data.get("criteria")
    if not isinstance(criteria, list) or not criteria:
        print("no criteria in verifier_data.json", file=sys.stderr)
        return 0.0

    try:
        from litellm import completion
    except ImportError:
        print("litellm unavailable in container", file=sys.stderr)
        return 0.0

    model = _resolve_model(data)
    n_total = len(criteria)
    n_pass = 0

    for i, crit in enumerate(criteria):
        if not isinstance(crit, dict):
            print(f"criterion[{i}] not a dict; treating as fail", file=sys.stderr)
            return 0.0
        question = crit.get("question")
        expected = str(crit.get("pass_criteria", "YES")).strip().upper()
        if expected not in ("YES", "NO"):
            expected = "YES"
        if not isinstance(question, str) or not question.strip():
            print(f"criterion[{i}] missing question; treating as fail", file=sys.stderr)
            return 0.0

        prompt = JUDGE_TEMPLATE.format(
            conversation=conversation, response=response_text, question=question
        )
        try:
            resp = completion(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                temperature=0,
                timeout=JUDGE_TIMEOUT_S,
            )
        except Exception as e:
            print(f"judge API error on criterion[{i}] ({model}): {e}", file=sys.stderr)
            return 0.0
        if not resp or not resp.choices:
            print(f"judge ({model}) returned no choices for criterion[{i}]", file=sys.stderr)
            return 0.0
        judge_output = (resp.choices[0].message.content or "").strip()
        verdict = _extract_verdict(judge_output)
        uid = crit.get("uid", i)
        print(f"criterion uid={uid} expected={expected} verdict={verdict} :: {judge_output[:200]!r}")
        if verdict is None:
            print(f"criterion[{i}] unparseable verdict; treating as fail", file=sys.stderr)
            return 0.0
        if verdict == expected:
            n_pass += 1
        else:
            # All-or-nothing: one failed criterion → reward 0. Short-circuit.
            print(f"criterion uid={uid} FAILED (got {verdict}, need {expected}) — overall fail")
            return 0.0

    print(f"All {n_pass}/{n_total} criteria passed — reward 1.0")
    return 1.0


if __name__ == "__main__":
    score = 0.0
    try:
        score = float(main())
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0.0
    _write_reward(score)
'''
