"""QA abstention verifier: extract \\boxed{...} from agent answer, normalized
text-compare against the gold answer.

Self-contained (no network / no LLM). Used for short-factoid QA datasets whose
system prompt instructs the model to box JUST the answer (and to box an
abstention token such as ``[IDK]`` when it does not know). Grading is purely
deterministic string comparison after a sensible normalization.

verifier_data.json keys:
  - expected_answer (str)         : the gold answer (REQUIRED).
  - abstention_token (str|None)   : if the gold answer IS the abstention token
                                    (i.e. the correct behavior is to abstain),
                                    set it here so abstaining scores 1. For an
                                    all-answerable dataset this is null and the
                                    agent must produce the real boxed gold.

Reward 1 when the extracted boxed answer matches the gold after normalization
(exact normalized equality, OR the normalized gold appears as a contiguous
token-subsequence of the normalized extracted answer — this lets an agent that
boxes e.g. "an estimated 15%" match a gold of "15%", or vice-versa, without
letting an unrelated short string pass). Reward 0 otherwise.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""QA \boxed{} normalized-text verifier — generated by nemotron_gym."""
from __future__ import annotations

import json
import pathlib
import re
import string
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")
MAX_ANSWER_BYTES = 64 * 1024


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _extract_boxed(text: str) -> str | None:
    # Find the LAST \boxed{...} with balanced braces.
    idx = text.rfind(r"\boxed{")
    if idx < 0:
        return None
    depth = 0
    start = idx + len(r"\boxed{")
    for i in range(start, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            if depth == 0:
                return text[start:i].strip()
            depth -= 1
    return None


_ARTICLES = re.compile(r"\b(a|an|the)\b")


def _normalize(s: str) -> str:
    s = s.lower()
    # Drop thousands separators inside numbers: 3,544 -> 3544
    s = re.sub(r"(?<=\d),(?=\d)", "", s)
    # Strip all punctuation (keeps alphanumerics + whitespace).
    s = "".join(ch for ch in s if ch not in string.punctuation)
    s = _ARTICLES.sub(" ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def _token_subseq(needle_tokens, hay_tokens) -> bool:
    """True if needle_tokens is a contiguous sublist of hay_tokens."""
    n, h = len(needle_tokens), len(hay_tokens)
    if n == 0 or n > h:
        return False
    for i in range(h - n + 1):
        if hay_tokens[i:i + n] == needle_tokens:
            return True
    return False


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_answer", "")
    if not isinstance(expected, str) or not expected.strip():
        print("expected_answer missing/empty", file=sys.stderr)
        return 0
    abstention_token = data.get("abstention_token")
    if not ANSWER.exists():
        print("/app/answer.txt missing — agent did not write answer", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")[:MAX_ANSWER_BYTES]
    extracted = _extract_boxed(raw)
    if extracted is None:
        # Fall back to whole content trimmed (agent may have skipped \boxed{}).
        extracted = raw.strip()
    print(f"expected={expected!r}")
    print(f"extracted={extracted!r}")
    if isinstance(abstention_token, str) and abstention_token:
        print(f"abstention_token={abstention_token!r}")

    got_n = _normalize(extracted)
    exp_n = _normalize(expected)
    print(f"got_normalized={got_n!r}")
    print(f"expected_normalized={exp_n!r}")

    if not got_n:
        print("verdict: empty extracted answer")
        return 0

    # Exact normalized equality.
    if got_n == exp_n:
        print("verdict: exact-normalized-match")
        return 1

    # Contiguous token-subsequence either direction (handles hedged golds like
    # "an estimated 15%" vs a bare "15%", and agents that box "the answer is X").
    got_t = got_n.split()
    exp_t = exp_n.split()
    if _token_subseq(exp_t, got_t):
        print("verdict: gold-is-token-subseq-of-answer")
        return 1
    if _token_subseq(got_t, exp_t):
        print("verdict: answer-is-token-subseq-of-gold")
        return 1

    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
