"""Regex-count verifier: apply each regex (MULTILINE) to /app/answer.txt and
reward 1 iff the total match count >= verify_min_matches.

Counting semantics (chosen to match the Nemotron free-form-formatting grader's
intent, where `mixed_*` patterns expect a SUMMED line count across several
line-anchored regexes — e.g. N key-value lines PLUS one `---` separator):

  - For each pattern in `verify_regex`, find all non-overlapping matches with
    re.MULTILINE.
  - If the pattern is LINE-ANCHORED (its source starts with `^`), the unit of
    counting is the matched LINE: we record the line-start offset of each match
    into a shared set. This dedupes the case where two anchored regexes in a
    `mixed_*` pattern both match the same physical line (e.g.
    `^- \\*\\*.+\\*\\*` and `^- .+` both matching `- **bold**`), so a line is
    counted at most once.
  - If the pattern is NOT line-anchored (inline patterns like `\\*\\*.+?\\*\\*`),
    the unit is each non-overlapping OCCURRENCE, which may repeat on one line.
  - total = (#distinct matched line-starts from anchored regexes)
            + (sum of occurrence counts from non-anchored regexes)
  - reward = 1 iff total >= verify_min_matches.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Regex-count verifier — generated by nemotron_gym."""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")
MAX_REGEX_LEN = 2048
MAX_REGEXES = 32
MAX_ANSWER_BYTES = 256 * 1024


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    regexes = data.get("verify_regex")
    min_matches = data.get("verify_min_matches")
    if not isinstance(regexes, list) or not regexes:
        print("verify_regex must be a non-empty list", file=sys.stderr)
        return 0
    if len(regexes) > MAX_REGEXES:
        print(f"too many regexes ({len(regexes)} > {MAX_REGEXES})", file=sys.stderr)
        return 0
    if not isinstance(min_matches, int) or min_matches < 1:
        print("verify_min_matches must be a positive int", file=sys.stderr)
        return 0
    for pat in regexes:
        if not isinstance(pat, str):
            print("verify_regex entries must be strings", file=sys.stderr)
            return 0
        if len(pat) > MAX_REGEX_LEN:
            print(f"regex too long ({len(pat)} > {MAX_REGEX_LEN})", file=sys.stderr)
            return 0

    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    text = ANSWER.read_text(errors="replace")[:MAX_ANSWER_BYTES]

    anchored_line_starts: set[int] = set()
    inline_occurrences = 0
    for pat in regexes:
        try:
            rx = re.compile(pat, re.MULTILINE)
        except re.error as e:
            print(f"regex compile error for {pat!r}: {e}", file=sys.stderr)
            return 0
        anchored = pat.startswith("^")
        count_here = 0
        for m in rx.finditer(text):
            count_here += 1
            if anchored:
                ls = text.rfind("\n", 0, m.start()) + 1
                anchored_line_starts.add(ls)
        if not anchored:
            inline_occurrences += count_here
        print(f"pattern {pat!r}: {count_here} match(es) anchored={anchored}")

    total = len(anchored_line_starts) + inline_occurrences
    score = 1 if total >= min_matches else 0
    print(f"total={total} min_matches={min_matches} verdict={'match' if score else 'mismatch'}")
    return score


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
