"""Multi-format structured-output verifier.

Grades an agent answer that must serialize a data structure in one of several
formats (json / yaml / toml / xml / csv) such that it conforms to a JSON Schema.

`schema_str` in the source dataset
(`nvidia/Nemotron-RL-Instruction-Following-Structured-Outputs-v2`) is ALWAYS a
JSON-Schema document; `schema_type` selects the *serialization format* the agent
must emit. Grading semantics per format:

  - json  : parse JSON, FULL JSON-Schema validation (Draft 2020-12). Strict.
  - yaml  : `yaml.safe_load` -> native python, date/datetime coerced to str,
            FULL JSON-Schema validation. Strict.
  - toml  : `tomllib.loads` -> native python, date/datetime coerced to str,
            FULL JSON-Schema validation. Strict.
  - xml   : well-formedness + STRUCTURAL check. There is no canonical lossless
            JSON<->XML mapping (no native int/bool/null typing, ambiguous
            arrays), so we do NOT attempt full schema validation. We require:
            (a) the answer parses as a single well-formed XML document, and
            (b) every top-level REQUIRED key from the schema appears as a
                descendant element tag (or attribute name) somewhere in the
                document. Documented limitation: types and nesting depth are
                NOT enforced for xml.
  - csv   : well-formedness + STRUCTURAL check. CSV is flat and cannot represent
            the nested objects/arrays these schemas contain, so we do NOT do
            full validation. We require: (a) the answer parses as CSV with a
            header row and >=1 data row, and (b) every top-level REQUIRED SCALAR
            key from the schema appears as a column header. Nested required keys
            (object/array typed) are not enforceable in flat CSV and are
            skipped. Documented limitation: types and nested structure are NOT
            enforced for csv.

For xml/csv the "required keys" are derived from the schema's top-level
`required`. That field is usually a list, but a sizeable minority of rows carry
a non-standard shape (e.g. ``{"item": ["a", "b"]}``); we flatten any list values
out of such a dict. If no usable required keys can be derived, we fall back to
the top-level `properties` keys (presence of ANY one is then sufficient, to
avoid a vacuous always-pass / always-fail).
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Multi-format structured-output verifier — generated by nemotron_gym.

verifier_data.json:
  {
    "schema": <jsonschema document, parsed dict>,
    "schema_type": "json" | "yaml" | "toml" | "xml" | "csv"
  }

Reads /app/answer.txt (optionally unwraps a ``` fence), parses per schema_type,
writes 1/0 to /logs/verifier/reward.txt.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

_FENCE = re.compile(r"```(?:[a-zA-Z0-9_+-]*)?\s*(.*?)```", re.DOTALL)


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _unwrap(raw: str) -> str:
    m = _FENCE.search(raw)
    return m.group(1) if m else raw


def _coerce_dates(obj):
    """yaml/toml parse dates/datetimes into native objects; schemas expect
    strings. Recursively stringify date/datetime/time leaves so `type: string`
    fields still validate."""
    import datetime as _dt

    if isinstance(obj, dict):
        return {k: _coerce_dates(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_coerce_dates(v) for v in obj]
    if isinstance(obj, (_dt.date, _dt.datetime, _dt.time)):
        return obj.isoformat()
    return obj


def _flatten_required(req):
    """Flatten a `required` value into a list of string key names, tolerating
    the non-standard `required: {group: [..]}` shape seen in this dataset."""
    keys: list = []
    if isinstance(req, list):
        keys = [k for k in req if isinstance(k, str)]
    elif isinstance(req, dict):
        for v in req.values():
            if isinstance(v, list):
                keys.extend(k for k in v if isinstance(k, str))
            elif isinstance(v, str):
                keys.append(v)
    return keys


def _required_keys(schema: dict) -> list:
    """Derive the set of top-level required key names from a schema."""
    return _flatten_required(schema.get("required"))


def _normalize_schema(node):
    """Recursively rewrite any non-standard dict-valued `required` (e.g.
    ``{"item": ["a","b"]}``) into the JSON-Schema-standard list form. Without
    this, jsonschema interprets a dict `required` as a property map and demands
    a literal property named ``item``/``field`` that no faithful answer carries,
    making ~1.4k rows unsatisfiable. Returns a normalized copy."""
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k == "required" and isinstance(v, dict):
                out[k] = _flatten_required(v)
            else:
                out[k] = _normalize_schema(v)
        return out
    if isinstance(node, list):
        return [_normalize_schema(v) for v in node]
    return node


def _validate_jsonschema(instance, schema: dict) -> int:
    try:
        from jsonschema import Draft202012Validator
    except ImportError as e:  # pragma: no cover
        print(f"jsonschema unavailable: {e}", file=sys.stderr)
        return 0
    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(instance), key=lambda e: list(e.path))
    if not errors:
        print("verdict: valid")
        return 1
    for err in errors[:5]:
        print(f"  err at {'/'.join(map(str, err.path))}: {err.message}")
    print(f"verdict: {len(errors)} validation error(s)")
    return 0


def _grade_json(text: str, schema: dict) -> int:
    try:
        instance = json.loads(text)
    except Exception as e:
        print(f"JSON parse error: {e}")
        return 0
    return _validate_jsonschema(instance, schema)


def _grade_yaml(text: str, schema: dict) -> int:
    try:
        import yaml
    except ImportError as e:
        print(f"pyyaml unavailable: {e}", file=sys.stderr)
        return 0
    try:
        instance = yaml.safe_load(text)
    except Exception as e:
        print(f"YAML parse error: {e}")
        return 0
    if instance is None:
        print("YAML parsed to None")
        return 0
    return _validate_jsonschema(_coerce_dates(instance), schema)


def _grade_toml(text: str, schema: dict) -> int:
    try:
        import tomllib
    except ImportError:  # pragma: no cover
        try:
            import tomli as tomllib  # type: ignore
        except ImportError as e:
            print(f"tomllib/tomli unavailable: {e}", file=sys.stderr)
            return 0
    try:
        instance = tomllib.loads(text)
    except Exception as e:
        print(f"TOML parse error: {e}")
        return 0
    return _validate_jsonschema(_coerce_dates(instance), schema)


def _grade_xml(text: str, schema: dict) -> int:
    import xml.etree.ElementTree as ET

    text = text.strip()
    try:
        root = ET.fromstring(text)
    except Exception as e:
        print(f"XML parse error (not well-formed): {e}")
        return 0
    # Collect every tag and attribute name in the document.
    seen = set()
    for el in root.iter():
        tag = el.tag
        if isinstance(tag, str):
            # strip any namespace prefix {ns}local -> local
            seen.add(tag.split("}")[-1])
        for attr in el.attrib:
            seen.add(attr.split("}")[-1])
    req = _required_keys(schema)
    if not req:
        # No required keys; fall back: any top-level property present is enough.
        props = list((schema.get("properties") or {}).keys())
        if not props:
            print("xml structural: no required/properties to check; well-formed -> pass")
            return 1
        if any(p in seen for p in props):
            print("xml structural: well-formed + >=1 schema property present")
            return 1
        print(f"xml structural: none of schema properties {props[:8]} found in tags/attrs")
        return 0
    missing = [k for k in req if k not in seen]
    if missing:
        print(f"xml structural: missing required element(s): {missing[:8]}")
        return 0
    print(f"xml structural: well-formed + all {len(req)} required keys present")
    return 1


def _grade_csv(text: str, schema: dict) -> int:
    import csv
    import io

    text = text.strip()
    if not text:
        print("CSV empty")
        return 0
    try:
        reader = csv.reader(io.StringIO(text))
        rows = [r for r in reader if any(c.strip() for c in r)]
    except Exception as e:
        print(f"CSV parse error: {e}")
        return 0
    if len(rows) < 2:
        print("CSV needs a header row and >=1 data row")
        return 0
    headers = {h.strip() for h in rows[0]}
    props = schema.get("properties") or {}
    req = _required_keys(schema)
    # Only enforce scalar required keys (CSV cannot represent nested objects/arrays).
    scalar_req = []
    for k in req:
        ty = (props.get(k) or {}).get("type")
        # ty may be a list like ["string","null"]; treat object/array as nested.
        types = ty if isinstance(ty, list) else [ty]
        if not any(t in ("object", "array") for t in types):
            scalar_req.append(k)
    if not scalar_req:
        # Nothing scalar to check; require at least one schema property header.
        prop_keys = list(props.keys())
        if not prop_keys:
            print("csv structural: no checkable keys; well-formed -> pass")
            return 1
        if headers & set(prop_keys):
            print("csv structural: well-formed + >=1 schema property column present")
            return 1
        print(f"csv structural: none of schema property columns {prop_keys[:8]} found")
        return 0
    missing = [k for k in scalar_req if k not in headers]
    if missing:
        print(f"csv structural: missing required column(s): {missing[:8]}")
        return 0
    print(f"csv structural: well-formed + all {len(scalar_req)} required scalar columns present")
    return 1


_GRADERS = {
    "json": _grade_json,
    "yaml": _grade_yaml,
    "toml": _grade_toml,
    "xml": _grade_xml,
    "csv": _grade_csv,
}


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    schema = data.get("schema")
    schema_type = data.get("schema_type")
    if not isinstance(schema, dict):
        print("schema must be object", file=sys.stderr)
        return 0
    grader = _GRADERS.get(schema_type)
    if grader is None:
        print(f"unsupported schema_type: {schema_type!r}", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    schema = _normalize_schema(schema)
    raw = ANSWER.read_text(errors="replace")
    candidate = _unwrap(raw)
    return grader(candidate, schema)


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
