"""SWE tool-call match verifier: agent emits JSON {name, arguments}, compared
to the gold next action of an in-progress OpenHands/codeact SWE trajectory.

Differs from the generic ``tool_call_match`` verifier in three SWE-specific ways:

1. Tool name is matched CASE-SENSITIVELY (exact). SWE tool names are fixed
   identifiers (``execute_bash``, ``str_replace_editor``, ``grep_files``, ...).

2. ``security_risk`` is a volatile, agent-self-assigned advisory label
   (observed values: ``LOW`` / ``MEDIUM`` / ``medium`` / even a free-text
   sentence; present in only ~42% of rows). It is NOT part of the action's
   semantics, so it is DROPPED from both the expected and candidate argument
   dicts before comparison.

3. String argument values (bash ``command``, ``path``, ``old_str``/``new_str``,
   ``pattern``, ...) are compared CASE-SENSITIVELY (lowercasing would make
   ``cd /Workspace`` == ``cd /workspace`` and ``import Numpy`` == ``import
   numpy`` — wrong for shell/code) but with WHITESPACE NORMALIZED (leading/
   trailing strip + internal runs of whitespace collapsed to a single space),
   so cosmetic spacing/indentation differences in an otherwise-identical
   command still pass. Non-string values (numbers like ``offset``/``limit``/
   ``view_range``, lists, nested dicts like ``todos``) are compared with exact
   equality.

This is a single-step argument comparison against the reference next action
(``agent_ref``: ``single_step_tool_use_with_argument_comparison_swe``); it does
NOT execute the tool or run repo tests.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""SWE single-step tool-call match verifier — generated by nemotron_gym.

The agent writes one JSON object to /app/answer.txt describing the next tool
call to make in an in-progress SWE agent conversation:
  {"name": "execute_bash", "arguments": {"command": "cd /workspace/... && ..."}}

The verifier compares it against verifier_data.json's `expected` (a list of
accepted tool calls; passes if ANY one matches). Matching semantics:
  - tool name: exact, case-sensitive
  - `security_risk` (volatile advisory label) dropped from both sides
  - remaining arg keys must match exactly
  - string values: case-sensitive, whitespace-normalized
  - non-string values: exact equality
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
# Fallback: a terminal agent may write its tool-call JSON to /app/response.txt
# instead of /app/answer.txt. Read both, prefer answer.txt.
RESPONSE = pathlib.Path("/app/response.txt")
DATA = pathlib.Path("/tests/verifier_data.json")

# Argument keys to ignore on BOTH sides (volatile / advisory, not semantic).
_IGNORE_KEYS = {"security_risk"}

_WS = re.compile(r"\s+")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _parse_arguments(args: object) -> dict | None:
    if isinstance(args, dict):
        return args
    if isinstance(args, str):
        try:
            v = json.loads(args)
            if isinstance(v, dict):
                return v
        except Exception:
            return None
    return None


def _drop_ignored(args: dict) -> dict:
    return {k: v for k, v in args.items() if k not in _IGNORE_KEYS}


def _norm_ws(s: str) -> str:
    return _WS.sub(" ", s).strip()


def _values_match(g: object, e: object) -> bool:
    if isinstance(e, str) and isinstance(g, str):
        return _norm_ws(e) == _norm_ws(g)
    # Exact equality for numbers / bools / lists / dicts / None.
    return e == g


def _args_match(got: dict, expected: dict) -> bool:
    g = _drop_ignored(got)
    e = _drop_ignored(expected)
    if set(g.keys()) != set(e.keys()):
        return False
    for k, ev in e.items():
        if not _values_match(g.get(k), ev):
            return False
    return True


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected", [])
    if not isinstance(expected, list) or not expected:
        print("expected calls missing", file=sys.stderr)
        return 0
    if ANSWER.exists():
        raw = ANSWER.read_text(errors="replace")
    elif RESPONSE.exists():
        print("/app/answer.txt missing; falling back to /app/response.txt")
        raw = RESPONSE.read_text(errors="replace")
    else:
        print("/app/answer.txt and /app/response.txt both missing", file=sys.stderr)
        return 0
    fence = re.search(r"```(?:json)?\s*(.*?)```", raw, flags=re.DOTALL)
    candidate = fence.group(1) if fence else raw
    try:
        got = json.loads(candidate)
    except Exception as e:
        print(f"agent did not emit valid JSON: {e}")
        return 0
    if not isinstance(got, dict):
        print(f"agent JSON not an object: {type(got).__name__}")
        return 0
    got_name = got.get("name")
    got_args = _parse_arguments(got.get("arguments"))
    if not isinstance(got_name, str) or got_args is None:
        print(f"agent JSON missing name/arguments: {got!r}")
        return 0
    print(f"agent call: name={got_name!r} args={_drop_ignored(got_args)!r}")
    for i, ec in enumerate(expected):
        if not isinstance(ec, dict):
            continue
        en = ec.get("name")
        ea = _parse_arguments(ec.get("arguments"))
        if not isinstance(en, str) or ea is None:
            continue
        print(f"  vs expected[{i}]: name={en!r} args={_drop_ignored(ea)!r}")
        if got_name == en and _args_match(got_args, ea):
            print("verdict: match")
            return 1
    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
