"""Additively add the 20 new nemotron-gym conversions to open-thoughts/TaskTrove as v3.

Keeps all 96 existing v2 dirs (NO deletes); adds 20 new org__name/ subdirs each
with tasks.parquet. Then updates README to v3. v2 is preserved at the `v2` tag.
"""
from __future__ import annotations
import shutil, os
from pathlib import Path
from huggingface_hub import HfApi
import pyarrow.parquet as pq

REPO = "open-thoughts/TaskTrove"
SRC = Path("/Users/benjaminfeuer/Documents/task_repos")
STAGE = Path("/Users/benjaminfeuer/Documents/task_repos/_tasktrove_v3_stage")

# local stem -> TaskTrove subdir (= laion repo id with / -> __)
MAP = {
    "instruction_following_citation": "laion__nemotron-gym-instruction-following-citation",
    "instruction_following_freeform": "laion__nemotron-gym-instruction-following-freeform",
    "litmus_bench": "laion__nemotron-gym-litmus-bench",
    "arc_agi_python_inductive": "laion__nemotron-gym-arc-agi-python-inductive",
    "reasoning_gym": "laion__nemotron-gym-reasoning-gym",
    "science_so_openq": "laion__nemotron-gym-science-so-openq",
    "agentic_function_calling_pivot": "laion__nemotron-gym-agentic-function-calling-pivot-v2",
    "agentic_conversational_tool_use_pivot": "laion__nemotron-gym-agentic-conversational-tool-use-pivot-v2",
    "agentic_swe_pivot": "laion__nemotron-gym-agentic-swe-pivot-v2",
    "agentic_indirect_prompt_injection": "laion__nemotron-gym-agentic-indirect-prompt-injection-v2",
    "arc_agi_transductive": "laion__nemotron-gym-arc-agi-transductive-v2",
    "structured_outputs_v3": "laion__nemotron-gym-structured-outputs-v4",
    "inverse_ifeval": "laion__nemotron-gym-inverse-ifeval-v2",
    "sysbench": "laion__nemotron-gym-sysbench-v2",
    "cfbench": "laion__nemotron-gym-cfbench-v2",
    "multiturnchat": "laion__nemotron-gym-instruction-following-multiturnchat-v2",
    "multichallenge_advanced": "laion__nemotron-gym-multichallenge-advanced-v2",
    "multichallenge_vanilla": "laion__nemotron-gym-multichallenge-vanilla-v2",
    "math_v3": "laion__nemotron-gym-math-v4",
    "qa_abstention": "laion__nemotron-gym-qa-abstention-v2",
}

README_V3 = """---
language:
- en
license: apache-2.0
task_categories:
- text-generation
size_categories:
- 100K<n<1M
tags:
- agent
- code
- agentic-tasks
- harbor
- reinforcement-learning
- swe-bench
---

# TaskTrove

**TaskTrove** is an open-source collection of agentic task datasets, released by the [OpenThoughts-Agent](https://www.open-thoughts.ai/blog/agent) team. It is the task complement to **[AgentTrove](https://huggingface.co/datasets/open-thoughts/AgentTrove)** — the agent traces in AgentTrove were generated by running models against these task datasets using the [Harbor](https://github.com/open-thoughts/OpenThoughts-Agent) framework.

> **v3 (this release)** — additive expansion of v2: all 96 v2 datasets are retained, plus **20 new Nemotron-Gym RLVR task datasets** converted from the [nvidia/Nemotron-Post-Training-v3](https://huggingface.co/collections/nvidia/nemotron-post-training-v3) collection (instruction-following, math, science, knowledge, reasoning, multi-turn chat, and single-step agentic pivots). Prior releases remain resolvable at the [`v1`](https://huggingface.co/datasets/open-thoughts/TaskTrove/tree/v1) and [`v2`](https://huggingface.co/datasets/open-thoughts/TaskTrove/tree/v2) tags.

---

## Repository Structure

Each source dataset is stored as a subdirectory named `org__name/`, where the original HuggingFace repo `org/name` has its `/` replaced with `__`. Each contains the task binaries as `tasks.parquet` (columns `path`: str, `task_binary`: gzip tar).

---

## Task Format

All tasks are valid [Harbor](https://github.com/open-thoughts/OpenThoughts-Agent) task binaries. Tasks fall into two categories:
- **With verifiers** (RL training / eval): a `verifier` scores trajectories at episode end.
- **Without verifiers** (SFT / datagen): define the environment + instruction, rely on external grading.

---

## New in v3: Nemotron-Gym RLVR conversions (20)

Converted with the OpenThoughts-Agent `data.nemotron_gym` framework. Grading is self-contained where the source carries a deterministic gold (string/regex/numeric/JSON-schema/grid), and LLM-judge where grading is inherently subjective (equivalence, rubric, hybrid IFEval+judge). Each task instruction explicitly directs the agent to write its answer to the grader's file path.

- Instruction-following: citation-formatting, free-form-formatting, structured-outputs (json/yaml/xml/toml/csv), multi-turn chat, adversarial inverse-IFEval, CFBench, SysBench
- Math / science / knowledge: math (sympy/latex boxed, with external-pointer hydration), litmus-bench (chemistry), science (Physics/Bio/Chem equivalence judge), QA-abstention, ReasoningGym, ARC-AGI (transductive + python-inductive), Multichallenge (advanced + vanilla)
- Single-step agentic pivots: function-calling, conversational-tool-use, SWE, indirect-prompt-injection (graded on the agent's next action)

---

## Usage

```bash
python -m scripts.datagen.extract_tasks_from_parquet \\
  --parquet open-thoughts/TaskTrove \\
  --output_dir $SCRATCH/tasks/tasktrove --on_exist overwrite
```

See the [OpenThoughts-Agent repository](https://github.com/open-thoughts/OpenThoughts-Agent) for the datagen/RL pipeline.

---

## Resolving prior versions

```python
from huggingface_hub import snapshot_download
snapshot_download(repo_id="open-thoughts/TaskTrove", repo_type="dataset", revision="v2", local_dir="./tasktrove_v2")  # or "v1"
```

---

## Citation

```bibtex
@misc{openthoughts-agent,
  author = {Team, OpenThoughts-Agent},
  month = Dec,
  title = {{OpenThoughts-Agent}},
  howpublished = {https://www.open-thoughts.ai/blog/agent},
  year = {2025}
}
```
"""


def main():
    api = HfApi()
    if STAGE.exists():
        shutil.rmtree(STAGE)
    STAGE.mkdir(parents=True)
    total = 0
    for stem, subdir in MAP.items():
        src = SRC / f"{stem}.parquet"
        assert src.exists(), f"missing {src}"
        d = STAGE / subdir
        d.mkdir(parents=True)
        shutil.copyfile(src, d / "tasks.parquet")
        total += pq.read_metadata(src).num_rows
    (STAGE / "README.md").write_text(README_V3)
    print(f"Staged {len(MAP)} subdirs, {total:,} tasks total. Uploading (additive)...")
    api.upload_folder(
        folder_path=str(STAGE),
        repo_id=REPO,
        repo_type="dataset",
        commit_message="v3: add 20 Nemotron-Gym RLVR task datasets (additive; v2 retained)",
        commit_description="All 96 v2 dirs kept; 20 new laion/nemotron-gym-* conversions added. v2 preserved at tag v2.",
        # NO delete_patterns -> purely additive
    )
    print("Upload complete.")


if __name__ == "__main__":
    raise SystemExit(main())
